### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by dkerr64** [HomeSpan/HomeSpan#1081]
I had a PR submitted to my RAGTDO32 project that enabled IPv6 support.  It is as basic as calling `WiFi.enableIPv6()` and in general "it just works" except it turns out it doesn't.

I believe that the issue is that we can have multiple IPv6 addresses assigned by a network, and that results in multiple callbacks to HomeSpan, specifically [here](https://github.com/HomeSpan/HomeSpan/blob/0a998cdccc22b0c3847e0de4462ffd221053c6af/src/HomeSpan.cpp#L467).  And every time that is called, the `connected` global is incremented.  The problem is that if it is odd, then the connection is assumed to be good, but if even it is assumed to be disconnected... which causes a loop of WiFi connection attempts.

So my ratgdo32 logs look like this (stripped down to just the relevant messages)
```
I (5.947) ratgdo-homekit: Status: WiFi connecting
Garage Door CDFB80 is READY!

Trying to connect to KSec.  Waiting 5 sec...
I (5.958) ratgdo-homekit: Wifi begin for SSID: KSec
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-43  BSSID=26:5A:4C:51:32:51)

Starting MDNS...

HostName:      Garage-Door-CDFB80.local:5556
Display Name:  Garage Door CDFB80
Model Name:    ratgdo-ESP32
Setup ID:      udm4

Starting HAP Server on port 5556...


DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP

I (8.878) ratgdo-homekit: WiFi established, count: 1, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: ::
I (8.895) ratgdo-homekit: Found 0 IPv6 addresses:
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-43  BSSID=26:5A:4C:51:32:51)
I (10.391) ratgdo-homekit: WiFi established, count: 1, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: fe80::da13:2aff:fecd:fb80
I (10.410) ratgdo-homekit: Found 1 IPv6 addresses:
I (10.415) ratgdo-homekit:   fe80::da13:2aff:fecd:fb80
I (10.419) ratgdo-homekit: Status: WiFi connecting
Trying to connect to KSec.  Waiting 8 sec...
I (10.960) ratgdo-homekit: Wifi begin for SSID: KSec
I (10.980) ratgdo-homekit: Status: WiFi connecting
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-46  BSSID=26:5A:4C:51:32:51)
I (13.676) ratgdo-homekit: WiFi established, count: 2, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: ::
I (13.693) ratgdo-homekit: Found 0 IPv6 addresses:
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-45  BSSID=26:5A:4C:51:32:51)
I (15.388) ratgdo-homekit: WiFi established, count: 2, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: fe80::da13:2aff:fecd:fb80
I (15.406) ratgdo-homekit: Found 1 IPv6 addresses:
I (15.411) ratgdo-homekit:   fe80::da13:2aff:fecd:fb80
I (15.414) ratgdo-homekit: Status: WiFi connecting
Trying to connect to KSec.  Waiting 13 sec...
I (19.180) ratgdo-homekit: Wifi begin for SSID: KSec
I (19.198) ratgdo-homekit: Status: WiFi connecting
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-46  BSSID=26:5A:4C:51:32:51)
I (21.890) ratgdo-homekit: WiFi established, count: 3, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: ::
I (21.911) ratgdo-homekit: Found 0 IPv6 addresses:
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-44  BSSID=26:5A:4C:51:32:51)
I (23.388) ratgdo-homekit: WiFi established, count: 3, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: fe80::da13:2aff:fecd:fb80
I (23.405) ratgdo-homekit: Found 1 IPv6 addresses:
I (23.409) ratgdo-homekit:   fe80::da13:2aff:fecd:fb80
I (23.413) ratgdo-homekit: Status: WiFi connecting
Trying to connect to KSec.  Waiting 22 sec...
I (32.691) ratgdo-homekit: Wifi begin for SSID: KSec
I (32.709) ratgdo-homekit: Status: WiFi connecting
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-47  BSSID=26:5A:4C:51:32:51)
I (36.420) ratgdo-homekit: WiFi established, count: 4, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: ::
I (36.438) ratgdo-homekit: Found 0 IPv6 addresses:
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-44  BSSID=26:5A:4C:51:32:51)
I (37.388) ratgdo-homekit: WiFi established, count: 4, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: fe80::da13:2aff:fecd:fb80
I (37.406) ratgdo-homekit: Found 1 IPv6 addresses:
I (37.410) ratgdo-homekit:   fe80::da13:2aff:fecd:fb80
I (37.413) ratgdo-homekit: Status: WiFi connecting
Trying to connect to KSec.  Waiting 36 sec...
I (54.899) ratgdo-homekit: Wifi begin for SSID: KSec
I (54.919) ratgdo-homekit: Status: WiFi connecting
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-47  BSSID=26:5A:4C:51:32:51)
I (57.624) ratgdo-homekit: WiFi established, count: 5, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: ::
I (57.641) ratgdo-homekit: Found 0 IPv6 addresses:
WiFi Connected!  IP Address = 192.168.21.89   (RSI=-44  BSSID=26:5A:4C:51:32:51)
I (59.390) ratgdo-homekit: WiFi established, count: 5, IP: 192.168.21.89, Mask: 255.255.255.0, Gateway: 192.168.21.3, DNS: 192.168.21.3 Link_IPv6: fe80::da13:2aff:fecd:fb80
I (59.407) ratgdo-homekit: Found 1 IPv6 addresses:
I (59.411) ratgdo-homekit:   fe80::da13:2aff:fecd:fb80
I (59.413) ratgdo-homekit: Status: WiFi connecting
```
And the looping over wifiBegin continues.

In this particular case I am connecting to a network that does not issue IPv6 addresses.  So the only IPv6 it finds is the link-local address.  If I connect to a network that issues IPv6 then it works.... but only because we get a link-local and a ULA (for my test network, I'm only issuing ULAs)... so an even number of IPv6 addresses, so `connected` is incremented twice, and so it settles down into a state where HomeSpan thinks it is properly connected.  But if I also provision the network to issue GUA's we're back to an odd number of IPv6 addresses.

I have not gone too deeply into how HomeSpan does the WiFi connect/disconnect.  Nor looked at ethernet.  But I think we need to rethink the whole `connected` being even/odd to indicate whether network is connected.

**Comment by HomeSpan** [comment]
I've done some more research and reviewed your PR.  Though the PR would resolve your immediate issue, it's not complete in that it does not provide for full support of IPv6, including displaying, etc. 

I've updated the code in the dev branch to provide full support for dual-stack use of IPv6 alongside of IPv4.  Simply include `WiFi.enableIPv6()` or `ETH.enableIPv6()` in your sketch (both are allowed at same time as well).

The new code checks for first receipt of an IP Address (either v4 or v6) and upon receiving it performs all the necessary steps.  If it then receives a second address, it reports that address but does not otherwise change the state of anything.  This ensures that the second address (whether IPv4 or IPv6) becomes useable as soon as it is available, but does not otherwise trigger anything in HomeSpan.

As you noted that there are multiple IPv6 addresses possible.  I coded the logic to look specifically for a UNIQUE LOCAL address instead of the LINK LOCAL since the latter does not seem to be useable in Safari (at least on my setup).  The UNIQUE LOCAL contains full details of the address (all 16 bytes) and if you enter it into Safari you can reach the HomeSpan Web Log as expected.

The ESP32 does not have a single command to returns the UNIQUE LOCAL address, so I added one to HomeSpan.  You can use `homeSpan.getUniqueLocalIPv6(WiFi)` or `homeSpan.getUniqueLocalIPv6(ETH)` to return this address as an IPAddress, so it works just like WiFi.localIP() and ETH.localIP() except it returns an IPv6 address.  If the address is not available, it returns all zeros, which is displayed as "::", per IPv6 conventions.

HomeSpan will now report both the IPv4 and IPv6 addresses in the interface as well as in the web logs.

I do not know if the Arduino IDE OTA functionality will work with IPv6, so something to check for in the future.

Please feel free to give it a try and let me know how it goes.

**Comment by dkerr64** [comment]
Thanks for the update, I'll take a look at your code when I get a chance.

Have you done anything for GUA's? The most common IPv6 scenario will have the network gateway issue GUAs (within delegated prefix from ISP).  And then any network that has Matter devices will likely also have ULAs issued by the Matter Controller or Thread Border Router.  I do not know what RFC has to say about priority... whether to use ULA over GUA when both are present on the network.

**Comment by apearson** [comment]
>  I do not know what RFC has to say about priority... whether to use ULA over GUA when both are present on the network.

https://www.rfc-editor.org/rfc/rfc6724#section-2.1

GUA > IPv4 > ULA 

> LINK LOCAL since the latter does not seem to be useable in Safari

You would need the interface identifier to tell Safari which link to use since WiFi and Ethernet could be on different LANs and IPv6 has just one standard link local prefix 

Example: http://[fe80::1%eth0]:5050

**Comment by HomeSpan** [comment]
The code I added to HomeSpan doesn't impact how the ESP32 manages the IPv6 stack.  If the device receives a global IPv6 it will use that according to however the Net-If and other ESP32 libraries use it. The only impact the new code has will be that the new code looks for a Unique Local address if an IPv6 is found, in order to configure additional HomeSpan logic if an IPv4 was not already found.  I could change this to look for either a Unique or Global address instead of just a Unique. 

My router does not provide a Global address when the ESP connects.  You can use WiFi.STA.PrintTo(Serial) to display all the details of the addresses found. 

I did try the % notation below but was not successful.  Maybe I'm not using the right zone?

Are you assigned a Global address when you connect to your network?

**Comment by dkerr64** [comment]
I built ratgdo32 with the dev branch of HomeSpan.  So far I am testing on a network that only has IPv4 and IPv6 ULAs (so have not tested with GUAs or both ULAs and GUAs).

The _Received IPv6 Address_ message is logged with the ULA received.

However, I am not getting a connection callback... I would have expected that?

Looking at your code, I still see logic based on even/odd connection count... I think that all has to go (e.g. it is the reason I'm not getting the connection callback).

**Comment by HomeSpan** [comment]
You will get the connection callback upon the device receiving the very first IP.  Can be either IPv4 or IPv6 ULA.   This seems to work fine on my sketches.  Note it is only called ONCE when transitioning from a disconnected state to a connected state.  Can you test with a minimal script, such as Example 1 with an added connection callback?

**Comment by HomeSpan** [comment]
Ah...that would be a completely different functionality.  The purpose of the connectivity callback is to allow the user to perform configurations once connectivity is established, and to track the number of times this occurs (hence the count).  It should not matter whether IPv4 or IPv6, or how many IPv6 addresses are received.  This is by design, else the user could wind up calling the config multiple times when not needed.  In other words, the callback is called exactly once per establishing or re-establishing a connection.

I think what you are looking for is a callback based on receiving a _new IP address_, even if already connected.  This would be a separate callback, and would serve a different purpose.   Without enabling IPv6, the connectionCallback serves the same purpose, but with IPv6 enabled, the two use-cases diverge.

Can you provide some context as to the use-case.  I could add a new callback based on that.

**Comment by HomeSpan** [comment]
Re your point about 3 IP Addresses, the code only calls the callback if it is NOT connected, per line 482 in HomeSpan.cpp: `if(!(connected%2)){...}`.  If the device is already connected, the entire block of code is skipped and connection is not incremented any further.

**Comment by HomeSpan** [comment]
As written the code only provides a log if it receives an IP4 or IPv6 ULA.  I've modified the code so that it reports on all IPv6 regardless of type.   Modified code just uploaded to dev branch.

**Comment by dkerr64** [comment]
> Can you provide some context as to the use-case. I could add a new callback based on that.
My personal preference would be to not create a new callback as the issuing (or changing) of IP Address(s) is all really a "connection" event.  I don't think there is a risk of break existing client code... multiple callbacks would occur only if IPv6 is enabled and no-one (other than me maybe!) has ventured on that yet.  And the callback code can handle it.

My use case is only that I want to show the IP addresses on the user interface for my device.  If IPv6 is enabled, then it is going to be preferred by HomeKit so it is helpful to know that.

**Comment by HomeSpan** [comment]
Thanks for the details on the use-case.  Note that the Espressif IDF and the Arduino-ESP32 library both consider the acquisition of an IP address to be distinct from a connectivity event.  To double-check this I added "Connection" events to the HomeSpan event handler with code to display the diagnostic message "Acquiring IP Addresses...".  Indeed this event is called just once by the ESP32 event handler, after which it makes three separate calls to the GOT_IP events to reflect the acquisition of each IP address (on my set-up, that's on IPv4, and two IPv6 - one for LINK Local and one for UNIQUE Local).

The reason I use the GOT_IP event to report full connectivity is that without an IP address, you can't yet use the IP stack, configure MDNS, etc.  The acquisition of subsequent IP Addresses does nothing to the actual connectivity, but it does silently get reflected in the ESP32 network stack.

One way to address your use-case would be to code your own WiFi callback directly in your sketch.  Callbacks are not unique - you can add more than one for the same sets of events, so this won't interfere with HomeSpan.  See the WiFiClientEvents sketch in the Arduino-ESP32 Examples, as provided by Espressif.

**Comment by dkerr64** [comment]
Okay, so we should be consistent with the platform.  If that means separate notification for IP address from connection then we should do that.

I'll have a look at adding my own WiFi callback, which would solve my use case without change to HomeSpan.

In the meantime, your code is still not logging correctly.  Example from my network...

```
Received IPv4 Address: 192.168.12.121
WiFi Connected! (RSI=-56  BSSID=26:5A:4C:31:32:51)

Starting MDNS...

HostName:      Garage-Door-CDFB80.local:5556
Display Name:  Garage Door CDFB80
Model Name:    ratgdo-ESP32
Setup ID:      udm4

Starting HAP Server on port 5556...


DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP

Received 1 IPv6 addresses
Received IPv6 Address: fe80::da13:2aff:fecd:fb80%st1
Received 3 IPv6 addresses
Received IPv6 Address: fdfb:1ca2:8f79:b847:da13:2aff:fecd:fb80
Received 3 IPv6 addresses
Received IPv6 Address: fdfb:1ca2:8f79:b847:da13:2aff:fecd:fb80
```

I added the log message to report number of IPv6 addresses received.  On this network both a ULA and GUA are being issued, so LLA+ULA+GUA = 3 IPv6 addresses... but both the GUA and ULA are being reported at the same time... or at least by the time we get around to calling `esp_netif_get_all_ip6()` on the second event, the 3rd IP address has been received.  And we cannot make any assumption on the order... the above log shows ULA addresses, but on some of my runs the GUA address is printed.

For logging purposes, We need to loop on the number of IPv6 addresses and just print them all each time.

**Comment by HomeSpan** [comment]
I think this is a ramification the how I implemented the queue reading from the core event handler.  I'll take a look.

**Comment by dkerr64** [comment]
I am able to use the `WiFi.onEvent()` callback to do what I need.  Unless you feel the need to fix logging, no more changes required in HomeSpan.

**Comment by HomeSpan** [comment]
Excellent!  However, I do need to fix the logging in any case.

The source of the problem is that I'm executing the event handler in the main HomeSpan thread as per ESP32 guidance since the WiFi.onEvent handler is executed from the WiFi thread and needs to be very quick.  So I simply pass the event message to the HomeSpan thread using a queue, which keeps the WiFi event handler very short and fast.  This generally works fine, and, as you observed, the GOT_IP handler gets called 3 times as expected.  But, it is not called fast enough to keep up with the number of IPs that have already been processed by the network library such that the total number of IPs reported equals three, even though GOT_IP may be only on its second iteration.

The logic I used attempts to find the IP that caused the event to trigger, so I call a function to return the number of addresses created and select the latest.  But for the reasons above, this does not work if multiple addresses are created before calls to GOT_IP can read them (with the result that the logging reports the third IP address created twice, and does not report the second IP address created at all).

There are a few solutions to this - I'll explore a little further and see which to use.  Will let you know when implemented so you can test for completeness.

Thanks for helping to debug all this!  My router does not issue a GUA so this issue did not surface on my setup.

**Comment by HomeSpan** [comment]
I believe I solved the logging issue.  Instead of just passing the event_id to my callback, I pass a full event structure, which contains additional info, including the specific IP6 address that triggered the GOT_IP6 event.  This simplifies the logic and means I don't have to count the number of IP6s already received to find the most recent.

Please give it a try and let me know if it works.  Also, you may want to use this same method in your own sketch when setting up your callback.

**Comment by dkerr64** [comment]
Yes, that makes sense.  I am getting the IP address the same way.

Let me know when you release this... I'm holding off publishing updates to my ratgdo32 firmware because I don't want to point it as a "dev" branch !!

Thanks.
